import { format, resolveConfig } from 'prettier'

export type RawExpression = {
  __raw: string
}

export type EmitOptions = {
  outPath: string
  builder: string
  sources: string[]
  imports: string
  body: string
}

export type EmittedModule = {
  outPath: string
  source: string
}

// Marks a value as an expression rather than data, so an id can be emitted as
// TransportMode.EScooter instead of a bare string. The generated file reads the
// way the hand written constant it replaces did.
export function raw(expression: string): RawExpression {
  return { __raw: expression }
}

function isRaw(value: object): value is RawExpression {
  return '__raw' in value
}

// Deliberately close to JSON.stringify: every key and string comes out double
// quoted, and prettier then applies the repo's quoteProps and singleQuote
// settings. Formatting rules live in .prettierrc, not here.
export function serialise(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(serialise).join(',')}]`
  }
  if (value !== null && typeof value === 'object') {
    if (isRaw(value)) return value.__raw
    const entries = Object.entries(value).map(
      ([key, item]) => `${JSON.stringify(key)}:${serialise(item)}`
    )
    return `{${entries.join(',')}}`
  }
  return JSON.stringify(value)
}

export async function emitModule(options: EmitOptions): Promise<EmittedModule> {
  const sources = options.sources.join(' and ')
  const header = [
    `// Generated by ${options.builder} from ${sources}.`,
    '// Do not edit by hand. Run `npm run data:build` to regenerate.',
  ].join('\n')

  const unformatted = [header, options.imports, options.body]
    .filter((part) => part !== '')
    .join('\n\n')

  // The repo forbids em and en dashes in every file, and this code writes
  // files. A Hebrew label that arrives with one is a source problem to fix in
  // the CSV, not something to let through.
  const dash = unformatted.match(/[\u2013\u2014]/)
  if (dash !== null) {
    throw new Error(`generated output for ${options.outPath} contains an em or en dash`)
  }

  const config = await resolveConfig(options.outPath)
  const source = await format(unformatted, {
    ...config,
    filepath: options.outPath,
    parser: 'typescript',
  })

  return { outPath: options.outPath, source }
}
