import { test } from 'node:test'
import assert from 'node:assert/strict'
import { emitModule, raw, serialise } from './emit'
import { dataPath } from './paths'

// Prettier resolves .prettierrc from the directory of the file it is formatting,
// so the fixture path has to sit inside src/data/ for the repo's settings to
// apply. Nothing is ever written to it.
const FIXTURE = dataPath('__emit_fixture__.ts')

test('serialise quotes keys and strings so prettier can unquote them', () => {
  assert.equal(serialise({ mode: 'קורקינט חשמלי' }), '{"mode":"קורקינט חשמלי"}')
})

test('serialise passes a raw expression through untouched', () => {
  assert.equal(serialise({ id: raw('TransportMode.EScooter') }), '{"id":TransportMode.EScooter}')
})

test('serialise handles nested arrays and objects', () => {
  assert.equal(serialise([{ a: [1, 2] }]), '[{"a":[1,2]}]')
})

test('emitModule writes a generated header naming its builder and sources', async () => {
  const { source } = await emitModule({
    outPath: FIXTURE,
    builder: 'scripts/data/buildExample.ts',
    sources: ['data/source/2026/severity.csv'],
    imports: "import type { Example } from '../types'",
    body: `export const EXAMPLE = ${serialise([{ a: 1 }])} satisfies Example[]`,
  })

  assert.match(source, /Generated by scripts\/data\/buildExample\.ts/)
  assert.match(source, /data\/source\/2026\/severity\.csv/)
  assert.match(source, /npm run data:build/)
})

test('emitModule returns source formatted to the repo prettier settings', async () => {
  const { source } = await emitModule({
    outPath: FIXTURE,
    builder: 'b.ts',
    sources: ['s.csv'],
    imports: "import type { Example } from '../types'",
    body: `export const EXAMPLE = ${serialise([{ a: 1 }])} satisfies Example[]`,
  })

  assert.match(source, /import type \{ Example \} from '\.\.\/types'/)
  assert.ok(!source.includes(';'), 'semi is false in .prettierrc')
  assert.ok(source.endsWith('\n'))
})

test('emitModule refuses an em dash anywhere in the output', async () => {
  await assert.rejects(
    emitModule({
      outPath: FIXTURE,
      builder: 'b.ts',
      sources: ['s.csv'],
      imports: '',
      body: 'export const A = "a \u2014 b"',
    }),
    /dash/
  )
})
