// Generated by scripts/data/buildMunicipalityTrend.ts from data/source/2026/municipality-trend.csv.
// Do not edit by hand. Run `npm run data:build` to regenerate.

import type { MunicipalityComparison } from '../types'

export const MUNICIPALITY_WORSENING = [
  { cityName: 'בית שמש', percentChange: '191.4' },
  { cityName: 'ביתר עילית', percentChange: '145.3' },
  { cityName: 'אשדוד', percentChange: '100.1' },
  { cityName: 'רחובות', percentChange: '88.2' },
  { cityName: 'חולון', percentChange: '69.0' },
  { cityName: 'אלעד', percentChange: '55.1' },
  { cityName: 'פתח תקווה', percentChange: '51.1' },
  { cityName: 'נתניה', percentChange: '40.4' },
  { cityName: 'חדרה', percentChange: '39.7' },
  { cityName: 'בת ים', percentChange: '39.5' },
  { cityName: 'בני ברק', percentChange: '29.7' },
  { cityName: 'אשקלון', percentChange: '28.0' },
  { cityName: 'לוד', percentChange: '23.7' },
  { cityName: 'באר שבע', percentChange: '12.2' },
  { cityName: 'ירושלים', percentChange: '2.5' },
] satisfies MunicipalityComparison[]

export const MUNICIPALITY_IMPROVING = [
  { cityName: 'רמלה', percentChange: '-22' },
  { cityName: 'ראשון לציון', percentChange: '-10' },
  { cityName: 'רמת גן', percentChange: '-10' },
  { cityName: 'חיפה', percentChange: '-7' },
  { cityName: 'תל אביב יפו', percentChange: '-5' },
] satisfies MunicipalityComparison[]
