// Generated by scripts/data/buildPeriods.ts from data/source/2026/severity.csv and data/source/2026/top-cities.csv.
// Do not edit by hand. Run `npm run data:build` to regenerate.

import type { ReportPeriods } from '../types'

export const REPORT_PERIODS = {
  previous: '2016-2021',
  current: '2021-2026',
} satisfies ReportPeriods
