// Generated by scripts/data/buildSummary.ts from data/source/2026/summary.csv.
// Do not edit by hand. Run `npm run data:build` to regenerate.

import type { SummaryFigure } from '../types'

export const REPORT_SUMMARY = [
  { label: 'סה״כ נפגעים', value: 6690, change: '+3.67%' },
  { label: 'פצועים קשה + הרוגים', value: 601, change: '+30%' },
] satisfies SummaryFigure[]
