// Generated by scripts/data/buildTransportation.ts from data/source/2026/severity.csv.
// Do not edit by hand. Run `npm run data:build` to regenerate.

import { TransportMode, type TransportationModeStats } from '../types'

export const TRANSPORTATION_MODES = [
  {
    id: TransportMode.EScooter,
    mode: 'קורקינט חשמלי',
    previousPeriod: { totalInjured: 182, lightInjuries: 163, severeInjuries: 16, deaths: 3 },
    currentPeriod: { totalInjured: 759, lightInjuries: 665, severeInjuries: 90, deaths: 4 },
    changes: {
      totalInjured: '+317%',
      lightInjuries: '+308%',
      severeInjuries: '+463%',
      deaths: '+33%',
    },
  },
  {
    id: TransportMode.Pedestrian,
    mode: 'הולכי רגל',
    previousPeriod: { totalInjured: 4280, lightInjuries: 3966, severeInjuries: 297, deaths: 17 },
    currentPeriod: { totalInjured: 4305, lightInjuries: 3917, severeInjuries: 365, deaths: 23 },
    changes: { totalInjured: '+1%', lightInjuries: '-1%', severeInjuries: '+23%', deaths: '+35%' },
  },
  {
    id: TransportMode.EBike,
    mode: 'אופניים חשמליים',
    previousPeriod: { totalInjured: 966, lightInjuries: 907, severeInjuries: 53, deaths: 6 },
    currentPeriod: { totalInjured: 690, lightInjuries: 629, severeInjuries: 59, deaths: 2 },
    changes: {
      totalInjured: '-29%',
      lightInjuries: '-31%',
      severeInjuries: '+11%',
      deaths: '-67%',
    },
  },
  {
    id: TransportMode.Bike,
    mode: 'אופניים רגילים',
    previousPeriod: { totalInjured: 990, lightInjuries: 925, severeInjuries: 61, deaths: 4 },
    currentPeriod: { totalInjured: 791, lightInjuries: 745, severeInjuries: 42, deaths: 4 },
    changes: { totalInjured: '-20%', lightInjuries: '-19%', severeInjuries: '-31%', deaths: '0%' },
  },
  {
    id: TransportMode.Scooter,
    mode: 'קורקינט לא חשמלי',
    previousPeriod: { totalInjured: 35, lightInjuries: 30, severeInjuries: 4, deaths: 1 },
    currentPeriod: { totalInjured: 145, lightInjuries: 133, severeInjuries: 12, deaths: 0 },
    changes: {
      totalInjured: '+314%',
      lightInjuries: '+343%',
      severeInjuries: '+200%',
      deaths: '-100%',
    },
  },
] satisfies TransportationModeStats[]
